# Termux-X terminal settings
# Copy target: ~/.termux/termux.properties

bell-character=ignore
fullscreen=false
use-black-ui=true
terminal-cursor-blink-rate=700
terminal-cursor-style=bar
terminal-margin-horizontal=4
terminal-margin-vertical=2

extra-keys = [ \
 ['ESC','CTRL','ALT','TAB','-','/','|'], \
 ['HOME','UP','END','PGUP','BKSP'], \
 ['LEFT','DOWN','RIGHT','PGDN','ENTER'] \
]
